seml:
  name: pprgo
  executable: run_seml.py
  output_dir: 'slurm_out'
  project_root_dir: .

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem: 16G                  # Main memory
    cpus-per-task: 5          # CPU cores
    time: 0-00:02             # Maximum runtime, D-HH:MM
    partition: [gpu_all]

fixed:
  data_dir: /nfs/shared/data/ # Directory containing .npz data files
  ntrain_div_classes: 20      # Number of training nodes divided by number of classes
  attr_normalization: None    # Attribute normalization. Not used in the paper
  #topk: 32                    # Number of PPR neighbors for each node
  ppr_normalization: 'sym'    # Adjacency matrix normalization for weighting neighbors
  #hidden_size: 32             # Size of the MLP's hidden layer
  #nlayers: 2                  # Number of MLP layers
  weight_decay: 1e-4          # Weight decay used for training the MLP
  dropout: 0.1                # Dropout used for training
  lr: 5e-3                    # Learning rate
  max_epochs: 200             # Maximum number of epochs (exact number if no early stopping)
  batch_size: 512             # Batch size for training
  batch_mult_val: 4           # Multiplier for validation batch size
  eval_step: 1                # Accuracy is evaluated after every this number of steps
  run_val: False              # Evaluate accuracy on validation set during training
  early_stop: False           # Use early stopping
  patience: 50                # Patience for early stopping
  nprop_inference: 2          # Number of propagation steps during inference
  inf_fraction: 1.0           # Fraction of nodes for which local predictions are computed during inference
  split_seed: 0               # Seed for splitting the dataset into train/val/test

cora:
  fixed:              # PPR teleport probability
    data_fname: 'cora_ml.npz'  # Name of .npz data file
    eps: 1e-2
    hidden_size: 64
    nlayers: 4
    topk: 64
    alpha: 0.25
    model_class: 'RobustPPRGo'
    aggr: 'sum'

# remaining:
#   fixed:
#     alpha: 0.25               # PPR teleport probability
#   grid:
#     data_fname:               # Name of .npz data file
#       type: choice
#       options:
#         - 'cora_full.npz'
#         - 'pubmed.npz'
#         - 'mag_large_filtered_06_09_coarse_standardized.npz'
#         # - 'mag_large_filtered_06_09_fine_standardized.npz'
